### ISSUE TITLE
What is the status of the port?

### ISSUE THREAD

**Issue by vhe1** [KSemenenko/ColorThief#1]
Hi!
Just asking, is this package already finished?
I would love to use it...

Lots of Greetings!
Volker

**Comment by KSemenenko** [comment]
Hi!
it works for Windows Universal App, but not for other platforms.

So, it's not finished yet but i am working on it to make it usable for all .net platforms.

Best regards)
Konstantin

**Comment by vhe1** [comment]
Actually I want to use it in an asp.net web service, so the full .net framework should be available. Would that be ok as well?
Lots of greetings!
Volker 

----- Ursprüngliche Nachricht -----
Von: "Kos" notifications@github.com
Gesendet: ‎07.‎01.‎2016 18:14
An: "KSemenenko/ColorThief" ColorThief@noreply.github.com
Cc: "vhe1" volker.hetzer@ieee.org
Betreff: Re: [ColorThief] What is the status of the port? (#1)

Hi!
it works for Windows Universal App, but not for other platforms.
So, it's not finished yet but i am working on it to make it usable for all .net platforms.
Best regards)
Konstantin

**Comment by KSemenenko** [comment]
within several days I'm planing to commit code for full .net framework and then it will definitely work properly. 

Best regards
Konstantin

**Comment by KSemenenko** [comment]
hi! 
please check, this version for .net

Best regards
 Konstantin

**Comment by vhe1** [comment]
Will do. Thanks a lot!

**Comment by vhe1** [comment]
Hi!
It's not a blocker but when I use `QuantizedColor col = thf.GetColor(Properties.Resources._20160107_Volker_Muster, 0, true);` I get a division by zero exception. Using 1 instead of 0 doesn't create an exception. The intellisense help says that 0 means "highest precision".

**Comment by KSemenenko** [comment]
thx, i will fix it!

**Comment by KSemenenko** [comment]
fixed
