### ISSUE TITLE
Setting quality to 0 throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by anderaus** [KSemenenko/ColorThief#2]
Good job, @KSemenenko! Thanks for doing this.

In the original js version of colorthief, the highest quality setting is 1. According to your code comments (example [here](https://github.com/KSemenenko/ColorThief/blob/master/ColorThief/ColorThief.cs#L39)), the highest quality setting in your ported version is 0. However, passing in 0 throws an IndexOutOfRangeException from GetPixelsFast.

I suggest correcting the code comments and adding a guard clause similar to the original [here](https://github.com/lokesh/color-thief/blob/master/src/color-thief.js#L100).

(I'll be happy to send a pull request)

**Comment by KSemenenko** [comment]
Hi, I will fix it!

**Comment by KSemenenko** [comment]
I that I fix it) in a few days will update nuget

**Comment by KSemenenko** [comment]
please check 1.0.0.1 version)

**Comment by anderaus** [comment]
Thanks, @KSemenenko! However, intellisense still refers to 0 as the minimum value. I guess the code comments need to be updated, too, like this one: https://github.com/KSemenenko/ColorThief/blob/master/ColorThief/ColorThief.cs#L39.

**Comment by KSemenenko** [comment]
Leave a comment

**Comment by KSemenenko** [comment]
Hi, @anderaus maby you can create pull request?

**Comment by anderaus** [comment]
Sure, @KSemenenko, I will get back to you with a PR

**Comment by KSemenenko** [comment]
@anderaus available on Nuget :)
