### ISSUE TITLE
Exception = {"Could not load file or assembly 'System.Runtime.WindowsRuntime, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.

### ISSUE THREAD

**Issue by niels9001** [KSemenenko/ColorThief#3]
I get the above exception when I add the latest NuGet version to a fresh UWP project, and when I do .GetPalette().

My test code:

> private async void Go()
>         {
>             string URL = "https://content.linkedin.com/content/dam/brand/site/img/color/color-palette-order.png";
>             Windows.Storage.Streams.IRandomAccessStream random = await Windows.Storage.Streams.RandomAccessStreamReference.CreateFromUri(new Uri(URL)).OpenReadAsync();
>             Windows.Graphics.Imaging.BitmapDecoder decoder = await Windows.Graphics.Imaging.BitmapDecoder.CreateAsync(random);

```
        ColorThief.ColorThief la = new ColorThief.ColorThief();
        List<QuantizedColor> colors = await la.GetPalette(decoder, 30, 10, false);

        foreach (QuantizedColor c in colors)
        {
            Rectangle rect = new Rectangle();
            rect.Width = 50;
            rect.Height = 50;

            Windows.UI.Color clr = new Windows.UI.Color() { A = c.Color.A, R = c.Color.R, B = c.Color.B, G = c.Color.G };
            rect.Fill = new SolidColorBrush(clr);
            gridView.Children.Add(rect);
        }
    }
```

Any thoughts?

**Comment by KSemenenko** [comment]
Hi, I will check it!

**Comment by niels9001** [comment]
Found the solution: the default NuGet package (Microsoft.NETCore.UniversalWindowsPlatform) had to be upgraded to the latest version (5.2.2) as well! 

Thanks!!!
